# Default config:
[API]
ListenAddress = "/ip4/127.0.0.1/tcp/11234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"
#
[Backup]
#  DisableMetadataLog = true
#
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/12340", "/ip6/::/tcp/12340"]
# for develop
#AnnounceAddresses = ["/ip4/103.44.253.2/tcp/15460","/ip4/183.240.204.123/tcp/15460","/ip4/47.56.139.17/tcp/15460"]
# for product
#AnnounceAddresses = ["/ip4/103.44.253.2/tcp/15470","/ip4/183.240.204.123/tcp/15470","/ip4/47.56.139.17/tcp/15470"]
#
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  ConnMgrLow = 15
#  ConnMgrHigh = 50
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false
UseIpfs = true
#  IpfsOnlineMode = false
#  IpfsMAddr = ""
IpfsMAddr = "/ip4/127.0.0.1/tcp/5001"
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]
#  DefaultMaxFee = "0.07 FIL"
#
[Chainstore]
#  EnableSplitstore = false
#  [Chainstore.Splitstore]
#    HotStoreType = "badger"
#    TrackingStoreType = ""
#    MarkSetType = ""
#    EnableFullCompaction = false
#    EnableGC = false
#    Archival = false
#
